#!/usr/bin/env python3

import time
import sys
import requests
# import parsel
# import keyboard
# import pygame
# import schedule


# def main():


def data_request():
    url = 'https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/cas-region.csv?'
    url = url + str(round(time.time()))
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36'}
    html = requests.get(url=url, headers=headers)
    html.encoding = 'UTF-8'
    print(html.encoding)
    text = html.text
    file_name = str(url.split('?')[-2].split('/')[-1]).split('.')[0] + '-' + time.strftime('%Y-%m-%d',
                                                                                           time.localtime()) + '.csv'

    with open(file_name, mode='w') as f:
        f.write(text)

data_request()
